version: '3'

services:
  flask1:
    build: .
    container_name: flask1
  flask2:
    build: .
    container_name: flask2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask1
      - flask2
